apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-rolebinding
  namespace: default  # Adjust namespace if different
subjects:
- kind: ServiceAccount
  name: default  # Adjust service account name if different
  namespace: default  # Adjust namespace if different
roleRef:
  kind: Role
  name: pod-reader-role  # Use the name of the Role created in step 1
  apiGroup: rbac.authorization.k8s.io

